server:
  port: 8080
app:
  endpoint:
    routers:
      character:
        url: ${URL_CHARACTER:http://localhost:8081/character/}
      location:
        url: ${URL_LOCATION:http://localhost:8081/location}